create table if not exists public.product_requests (
  id bigint generated by default as identity primary key,
  full_name text not null,
  tshirt_design integer not null check (tshirt_design between 1 and 5),
  tshirt_size text not null check (tshirt_size in ('XS','S','M','L','XL','2XL','3XL')),
  polar_design integer not null check (polar_design between 1 and 5),
  polar_size text not null check (polar_size in ('XS','S','M','L','XL','2XL','3XL')),
  status text not null default 'Yeni' check (status in ('Yeni', 'Onaylandı', 'Hazırlanıyor', 'Tamamlandı')),
  created_at timestamptz not null default now()
);

alter table public.product_requests enable row level security;

-- Site yalnızca sunucu tarafındaki service-role anahtarıyla erişir.
