create table if not exists public.product_requests (
  id bigint generated by default as identity primary key,
  full_name text not null,
  product text not null check (product in ('Tişört', 'Polar')),
  department text not null check (department in ('NETWORK', 'SECURITY', 'SYSTEM')),
  color text not null,
  size text not null,
  design_variant integer not null check (design_variant between 1 and 5),
  quantity integer not null default 1 check (quantity between 1 and 10),
  note text not null default '',
  status text not null default 'Yeni' check (status in ('Yeni', 'Onaylandı', 'Hazırlanıyor', 'Tamamlandı')),
  created_at timestamptz not null default now()
);

alter table public.product_requests enable row level security;

-- Site yalnızca sunucu tarafındaki service-role anahtarıyla erişir.
